name: digital-engagement-analytics
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - xgboost
  - lightgbm
  - shap
  - feature-engine
  - tabulate
  - jupyterlab